server:
  port: 8080

spring:
  application:
    name: gateway-server
  profiles:
    active: main
  config:
    import: optional:configserver:http://admin:1234@localhost:8888

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - name: company-service
        url: /company-service/v3/api-docs
      - name: user-service
        url: /user-service/v3/api-docs
      - name: estimate-service
        url: /estimate-service/v3/api-docs
      - name: matching-service
        url: /matching-service/v3/api-docs

resilience4j:
  circuitbreaker:
    configs:
      main:
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
    instances:
      companyCircuitBreaker:
        baseConfig: main
      matchingCircuitBreaker:
        baseConfig: main
  timelimiter:
    configs:
      main:
        timeoutDuration: 5s