server:
  port: 8080

spring:
  application:
    name: gateway-server

  # Spring Config Server에서 설정을 가져올 때 사용
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:

        # --- company-service API & Swagger ---
        - id: company-api
          uri: lb://company-service
          predicates:
            - Path=/company-service/api/companies/**

        - id: company-swagger
          uri: lb://company-service
          predicates:
            - Path=/company-service/v3/api-docs/**
            - Path=/company-service/swagger-ui.html
            - Path=/company-service/swagger-ui/**

        # --- user-service API & Swagger ---
        - id: user-api
          uri: lb://user-service
          predicates:
            - Path=/user-service/api/users/**

        - id: user-swagger
          uri: lb://user-service
          predicates:
            - Path=/user-service/v3/api-docs/**
            - Path=/user-service/swagger-ui.html
            - Path=/user-service/swagger-ui/**

        # --- estimate-service API & Swagger ---
        - id: estimate-api
          uri: lb://estimate-service
          predicates:
            - Path=/estimate-service/api/estimates/**

        - id: estimate-swagger
          uri: lb://estimate-service
          predicates:
            - Path=/estimate-service/v3/api-docs/**
            - Path=/estimate-service/swagger-ui.html
            - Path=/estimate-service/swagger-ui/**

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/