server:
  port: 8080

spring:
  application:
    name: gateway-server

  # Spring Config Server에서 설정을 가져올 때 사용
  config:
    import: "optional:configserver:http://config:8888"

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false   # 자동 라우팅 끔
      routes:
        - id: company
          uri: lb://company-service
          predicates:
            - Path=/company/**
          filters:
            - StripPrefix=1

        - id: user
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1

        - id: Test1
          uri: lb://ms1
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/


