server:
  port: 8082

spring:
  application:
    name: ms1
  profiles:
    active: dev
  config:
    import:
      - optional:configserver:http://admin:1234@localhost:8888

  datasource:
    url: jdbc:mysql://localhost:3306/BizOnDam
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/