spring:
  application:
    name: company-service
  profiles:
    active: dev
  config:
    import:
      - "optional:configserver:http://admin:1234@localhost:8888"

mybatis:
  mapper-locations: classpath:mybatis.mapper/*.xml

jasypt:
  encryptor:
    password: ${ENCRYPTOR_PASSWORD}

# API 키 등록
national-tax:
  api-url: https://api.odcloud.kr/api/nts-businessman/v1/validate
  service-key: ${NATIONAL_TAX_API_KEY}
  return-type: JSON
