spring:
  application:
    name: company-service
  datasource:
    url: jdbc:mysql://localhost:3306/bizondam
    username: root
    password: Qlvh0423!
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
