server:
  port: 8081
  servlet:
    context-path: /user-service

spring:
  application:
    name: user-service
  profiles:
    active: dev
  config:
    import:
      - "optional:configserver:http://admin:1234@localhost:8888"

mybatis:
  mapper-locations: classpath:mybatis.mapper/*.xml

jasypt:
  encryptor:
    password: ${ENCRYPTOR_PASSWORD}