# peer1 인스턴스 (8761)
spring:
  config:
    activate:
      on-profile: peer1
  application:
    name: eureka-server

server:
  port: 8761

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
  server-url:
    defaultZone: http://localhost:8762/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,env
---
# peer2 인스턴스 (8762)
spring:
  config:
    activate:
      on-profile: peer2
  application:
    name: eureka-server

server:
  port: 8762

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
  server-url:
    defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,env
