spring:
  application:
    name: eureka-server
  profiles:
    active: peer1
  config:
      import: optional:configserver:http://admin:1234@localhost:8888
  security:
    user:
      name: eureka
      password: eurekapwd

# 관리용 엔드포인트(health, info, env)
management:
  endpoints:
    web:
      exposure:
        include: health,info,env